name: aicex ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: wulffern/aicex:22.04_0.1.4
      options: --user root
    steps:
      - name: aicex
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Run tests
        run: |
          /bin/bash tests/run_docker_test.sh
